# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 noah
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "calibre_web_base_path", "new": "<Removed>" }
    - { "old": "calibre_web_environment_variables_extension", "new": "calibre_web_environment_variables_additional_variables" }

- name: Fail if required Calibre-Web settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - calibre_web_identifier
    - calibre_web_uid
    - calibre_web_gid
    - calibre_web_hostname
    - calibre_web_path_prefix
    - calibre_web_container_network

- name: Validate Calibre-Web Traefik configuration
  when: calibre_web_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Calibre-Web Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - calibre_web_container_labels_traefik_hostname
        - calibre_web_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `calibre_web_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if calibre_web_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          calibre_web_container_labels_traefik_path_prefix (`{{ calibre_web_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/calibre_web`).
      when: "calibre_web_container_labels_traefik_path_prefix != '/' and calibre_web_container_labels_traefik_path_prefix[-1] == '/'"

    - name: Fail if calibre_web_path_prefix is anything other than /
      ansible.builtin.fail:
        msg: >-
          `calibre_web_path_prefix` must be set to `/`.
          See the comments for the `calibre_web_path_prefix` variable in `defaults/main.yml`.
          Hosting calibre_web at a subdirectory may or may not work as expected - it will most likely require additional work.
      when: "calibre_web_path_prefix != '/'"
